assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: GI01SUMO-RII11-02-PHSENE042
stream:
  method: recovered_host
  name: phsen_abcdef_imodem_control_recovered
workflow_config:
  schedule: 0 0 * * *
